# Generated by Django 3.2.7 on 2021-10-25 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0001_initial'),
        ('App_Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Shop.product'),
        ),
    ]
